### ISSUE TITLE
Configure CI and write scripts

### ISSUE THREAD

**Issue by Osky772** [handsontable/code-snippets#2]
### Description

In the current repo configure CI (Github Actions) on [manual triggers](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/) that will run commands for each template and example project:
1. `npm install`
2. `npm run test` 
3. `npm run build`
4. deploy examples to the Github Pages

### Tasks
- [x] write a script that for each code example in the repo will run 3 commands from above (`npm install`, `npm run test`, `npm run build`)
- [x] configure Github Actions on manual triggers to run the script from the `package.json`
- [x] deploy all examples to the Github Pages (configure + script)
- [ ] on push to the develop branch - build all the example apps; on push to the master (aka release) - deploy all the examples to the Github Pages (discuss that first)
- [x] make a script that will copy build project assets to the GH Pages deploy folder
- [x] make a script that will update Handsontable in all projects as well as `package.json` of each project (+ make input in Github Actions manual workflow to update HOT directly from Github Actions)

More info - https://kb.handsontable.com/display/PROJ/Environment+for+code+snippets

**Comment by Osky772** [comment]
Closing this issue. New issues will be created with tasks specified on 21 Jan 2021 - https://kb.handsontable.com/display/PROJ/Environment+for+code+snippets.
